# VPS Lama — dialihfungsikan sementara sebagai Staging Server (~1 minggu)
[staging]
43.133.131.141 ansible_user=ubuntu

# VPS Baru — Production Server permanen
[production]
43.173.11.38 ansible_user=ubuntu

[all:vars]
ansible_ssh_transfer_method=scp
